language: node_js
node_js: 
  - "node"
install: 
  - npm install
script: 
  - npm test
  - ./node_modules/karma/bin/karma start
  - istanbul cover ./node_modules/mocha/bin/_mocha server/api/**/*.spec.js
  - cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
after_success: npm run coverage
